name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  checks: write
  contents: read
  actions: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Convert Playwright report to CTRF
      if: ${{ !cancelled() }}
      run: node convert-to-ctrf.mjs results.json ctrf-report.json
    - name: Test Report
      uses: ctrf-io/github-test-reporter@v1
      if: ${{ !cancelled() }}
      with:
        report-path: './ctrf-report.json'
        github-report: true
        summary-report: true
        test-report: true
        test-list-report: true
        flaky-report: true
        failed-report: true
        failed-folded-report: true
        skipped-report: true
        suite-folded-report: true
        suite-list-report: true
